source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'activerecord', '5.2.3'
gem 'bcrypt'
gem 'rake'
gem 'sinatra-activerecord'
gem 'pry'
gem 'pry-byebug'

gem 'active_model_otp'
gem 'cloudinary'
gem 'json'
gem 'dotenv'
gem 'rqrcode'
gem 'rqrcode_png'

gem "sinatra-cross_origin", "~> 0.3.1"

group :development do
  gem 'sqlite3', '1.4.1'
end

group :production do
  gem 'pg', '0.21.0'
end